# @package _global_

defaults:
  - base_config
  - _self_

data:
  _target_: verl.configs.vizwiz_vqa.VizWizDataConfig
  train_files: []  # Will be set by command line
  val_files: []    # Will be set by command line
  train_batch_size: 32
  val_batch_size: 64
  max_prompt_length: 256
  max_response_length: 128
  image_size: 480
  num_workers: 4
  dataset_type: "vizwiz"
  dataset_config:
    processor_name: "microsoft/git-base-vqav2"
    max_prompt_length: 256
    max_response_length: 128
    image_size: 480

model:
  _target_: verl.configs.vizwiz_vqa.VizWizModelConfig
  path: ${actor_rollout_ref.model.path}
  vision_tower: null
  use_flash_attention: true
  load_in_8bit: false
  load_in_4bit: false

trainer:
  _target_: verl.trainer.config.TrainerConfig
  n_gpus_per_node: 1
  nnodes: 1
  save_freq: 10
  test_freq: 10
  total_epochs: 2
  project_name: "TinyZero"
  experiment_name: "vizwiz_vqa_ppo_test"
  logger: ["wandb"]
  val_before_train: true
  default_hdfs_dir: null

algorithm:
  _target_: verl.algorithm.config.AlgorithmConfig
  kl_ctrl:
    kl_coef: 0.001

hydra:
  run:
    dir: outputs/${trainer.experiment_name}
